{{- if .Values.deployment.create }}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ml-pipeline-scheduledworkflow
  namespace: {{ .Release.Namespace }}
  labels:
    component: ml-pipeline-scheduledworkflow
{{ include "pipelines.commonLabels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      component: ml-pipeline-scheduledworkflow
{{ include "pipelines.commonLabels" . | indent 6 }}
  template:
    metadata:
      labels:
        component: ml-pipeline-scheduledworkflow
{{ include "pipelines.commonLabels" . | indent 8 }}
    spec:
      containers:
        - image: {{ .Values.images.scheduledworkflow.repository }}:{{ .Values.images.scheduledworkflow.tag }}
          imagePullPolicy: {{ .Values.images.imagePullPolicy }}
          name: ml-pipeline-scheduledworkflow
          namespace: {{ .Release.Namespace }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      serviceAccountName: ml-pipeline-scheduledworkflow
      resources:
{{ toYaml .Values.resources.scheduledWorkflow | indent 8 }}
{{- end }}
