apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: passwords.dex.coreos.com
  labels:
    {{- include "dex-crds.labels" . | nindent 4 }}
spec:
  group: dex.coreos.com
  version: v1
  scope: Namespaced
  names:
    plural: passwords
    singular: password
    kind: Password
