{{- if .Values.deployment.create }}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    component: ml-pipeline
{{ include "pipelines.commonLabels" . | indent 4 }}
  name: ml-pipeline
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      component: ml-pipeline
{{ include "pipelines.commonLabels" . | indent 6 }}
  template:
    metadata:
      labels:
        component: ml-pipeline
{{ include "pipelines.commonLabels" . | indent 8 }}
    spec:
      containers:
      - name: ml-pipeline-api-server
        env:
        - name: OBJECTSTORECONFIG_ACCESSKEY
          value: "{{ .Values.configurations.credentials.accessKey }}"
        - name: OBJECTSTORECONFIG_SECRETACCESSKEY
          value: minio123
        - name: OBJECTSTORECONFIG_BUCKETNAME
          value: "{{ .Values.storage.artifacts.containerName }}"
        - name: OBJECTSTORECONFIG_PORT
          value: "{{ .Values.configurations.ports.nginxPort }}"
        - name: OBJECTSTORECONFIG_HOST
          value: v3io-webapi
        - name: OBJECTSTORECONFIG_MULTIPART_DISABLE
          value: "true"
        - name: OBJECTSTORECONFIG_FORCEV2SIGNATURE
          value: "true"
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: {{ .Values.images.apiServer.repository }}:{{ .Values.images.apiServer.tag }}
        imagePullPolicy: {{ .Values.images.imagePullPolicy }}
        ports:
        - containerPort: 8888
        - containerPort: 8887
      serviceAccountName: ml-pipeline
      resources:
{{ toYaml .Values.resources.apiServer | indent 8 }}
{{- end }}
