{{- if and .Values.persistence.enabled (eq .Values.persistence.type "v3io") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-v3io-fuse
  labels:
    app: {{ template "grafana.name" . }}
    chart: {{ template "grafana.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: v3io/fuse
data:
{{ include "v3io-configs.fuse.secret" . | indent 2 }}
{{- end -}}
