{{- if .Values.serviceAccounts.api.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mlrun.serviceAccountName.api" . }}
  labels:
{{ include "mlrun.api.labels" . | nindent 4 }}
{{- end -}}
