apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-v3io-fuse
  labels:
{{ include "mlrun.common.labels" . | nindent 4 }}
type: v3io/fuse
data:
{{ include "v3io-configs.fuse.secret" . | indent 2 }}
