{{- if .Values.crd.create }}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: workflows.argoproj.io
  labels:
    component: crd
{{ include "pipelines.commonLabels" . | indent 4 }}
spec:
  group: argoproj.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: Workflow
    plural: workflows
    shortNames:
    - wf
{{- end }}
