{{- if .Values.rbac.create }}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: mysql
  labels:
    component: mysql-kf
{{ include "pipelines.commonLabels" . | indent 4 }}
spec:
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
      protocol: TCP
  selector:
    component: mysql-kf
{{ include "pipelines.commonLabels" . | indent 4 }}
{{- end }}
