{{- if .Values.deployment.create }}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ml-pipeline-viewer-crd
  namespace: {{ .Release.Namespace }}
  labels:
    component: ml-pipeline-viewer-crd
{{ include "pipelines.commonLabels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      component: ml-pipeline-viewer-crd
{{ include "pipelines.commonLabels" . | indent 6 }}
  template:
    metadata:
      labels:
        component: ml-pipeline-viewer-crd
{{ include "pipelines.commonLabels" . | indent 8 }}
    spec:
      containers:
      - image: {{ .Values.images.viewerCrdController.repository }}:{{ .Values.images.viewerCrdController.tag }}
        imagePullPolicy: {{ .Values.images.imagePullPolicy }}
        name: ml-pipeline-viewer-crd
        env:
        - name: MAX_NUM_VIEWERS
          value: "50"
        - name: MINIO_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      serviceAccountName: ml-pipeline-viewer-crd-service-account
      resources:
{{ toYaml .Values.resources.viewerCRD | indent 8 }}
{{- end }}
