apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "jupyter.name" . }}
    chart: {{ template "jupyter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "jupyter.mpijobexecutor" . }}

