apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "shell.name" . }}
    chart: {{ template "shell.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "shell.svcadmin" . }}

