{{- if .Values.deployment.create }}
apiVersion: v1
kind: Service
metadata:
  name: metadata-service
  namespace: {{ .Release.Namespace }}
  labels:
    component: metadata
{{ include "pipelines.commonLabels" . | indent 4 }}
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: md-backendapi
  type: ClusterIP
  selector:
    component: metadata-server
{{ include "pipelines.commonLabels" . | indent 4 }}
{{- end }}
