{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeflow-pipelines-metadata-writer
  namespace: {{ .Release.Namespace }}
  labels:
    component: metadata-writer
{{ include "pipelines.commonLabels" . | indent 4 }}
{{- end }}
