{{- if .Values.deployment.create }}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: metadata-writer
  namespace: {{ .Release.Namespace }}
  labels:
    component: metadata-writer-server
{{ include "pipelines.commonLabels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: metadata-writer-server
{{ include "pipelines.commonLabels" . | indent 6 }}
  template:
    metadata:
      labels:
        component: metadata-writer-server
{{ include "pipelines.commonLabels" . | indent 8 }}
    spec:
      containers:
      - name: main
        image: {{ .Values.images.metadataWriter.repository }}:{{ .Values.images.metadataWriter.tag }}
        imagePullPolicy: {{ .Values.images.imagePullPolicy }}
        env:
        - name: NAMESPACE_TO_WATCH
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      serviceAccountName: kubeflow-pipelines-metadata-writer
      resources:
{{ toYaml .Values.resources.metadataWriter | indent 8 }}
{{- end }}
