name: CI

on: [push, pull_request]

env:
  HELM_REPO: "https://get.helm.sh"
  HELM_BIN: "helm-v3.2.0-linux-amd64.tar.gz"

jobs:

  test:
    name: Test charts
    runs-on: ubuntu-latest
    steps:
    - name: Install Helm
      run: |
        wget -q ${HELM_REPO}/${HELM_BIN}
        tar xzvf ${HELM_BIN}
        chmod +x ./linux-amd64/helm
        sudo mv ./linux-amd64/helm /usr/local/bin/

    - name: helm version
      run: helm version

    - name: Add Helm repos
      run: |
        helm repo add stable https://kubernetes-charts.storage.googleapis.com
        helm repo add nuclio https://nuclio.github.io/nuclio/charts
        helm repo add v3io-stable https://v3io.github.io/helm-charts/stable

    - uses: actions/checkout@v2

    - name: Test stable
      run: make stable

    - name: Test demo
      run: make demo
