{{- if .Values.deployment.create }}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ml-pipeline-ui
  namespace: {{ .Release.Namespace }}
  labels:
    component: ml-pipeline-ui
{{ include "pipelines.commonLabels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      component: ml-pipeline-ui
{{ include "pipelines.commonLabels" . | indent 6 }}
  template:
    metadata:
      labels:
        component: ml-pipeline-ui
{{ include "pipelines.commonLabels" . | indent 8 }}
    spec:
      containers:
      - image: {{ .Values.images.ui.repository }}:{{ .Values.images.ui.tag }}
        imagePullPolicy: {{ .Values.images.imagePullPolicy }}
        name: ml-pipeline-ui
        ports:
        - containerPort: 3000
        env:
          - name: MINIO_V3IO
            value: "1"
          - name: MINIO_PORT
            value: "{{ .Values.configurations.ports.nginxPort }}"
          - name: MINIO_HOST
            value: v3io-webapi
          - name: MINIO_ACCESS_KEY
            value: minio
          - name: HTTP_AUTHORIZATION_KEY
            value: X-v3io-session-key
          - name: HTTP_AUTHORIZATION_DEFAULT_VALUE
            value: "{{ .Values.configurations.credentials.accessKey }}"
          - name: MINIO_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: DISABLE_GKE_METADATA
            value: "true"
      serviceAccountName: ml-pipeline-ui
      resources:
{{ toYaml .Values.resources.ui | indent 8 }}
{{- end }}
